# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yx/fr/project/imageParser

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yx/fr/project/imageParser

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yx/fr/project/imageParser/CMakeFiles /home/yx/fr/project/imageParser/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yx/fr/project/imageParser/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named feature

# Build rule for target.
feature: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 feature
.PHONY : feature

# fast build rule for target.
feature/fast:
	$(MAKE) -f CMakeFiles/feature.dir/build.make CMakeFiles/feature.dir/build
.PHONY : feature/fast

#=============================================================================
# Target rules for targets named imageParser

# Build rule for target.
imageParser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 imageParser
.PHONY : imageParser

# fast build rule for target.
imageParser/fast:
	$(MAKE) -f CMakeFiles/imageParser.dir/build.make CMakeFiles/imageParser.dir/build
.PHONY : imageParser/fast

clcnst/clcnst.o: clcnst/clcnst.cpp.o
.PHONY : clcnst/clcnst.o

# target to build an object file
clcnst/clcnst.cpp.o:
	$(MAKE) -f CMakeFiles/feature.dir/build.make CMakeFiles/feature.dir/clcnst/clcnst.cpp.o
.PHONY : clcnst/clcnst.cpp.o

clcnst/clcnst.i: clcnst/clcnst.cpp.i
.PHONY : clcnst/clcnst.i

# target to preprocess a source file
clcnst/clcnst.cpp.i:
	$(MAKE) -f CMakeFiles/feature.dir/build.make CMakeFiles/feature.dir/clcnst/clcnst.cpp.i
.PHONY : clcnst/clcnst.cpp.i

clcnst/clcnst.s: clcnst/clcnst.cpp.s
.PHONY : clcnst/clcnst.s

# target to generate assembly for a file
clcnst/clcnst.cpp.s:
	$(MAKE) -f CMakeFiles/feature.dir/build.make CMakeFiles/feature.dir/clcnst/clcnst.cpp.s
.PHONY : clcnst/clcnst.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/imageParser.dir/build.make CMakeFiles/imageParser.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/imageParser.dir/build.make CMakeFiles/imageParser.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/imageParser.dir/build.make CMakeFiles/imageParser.dir/main.cpp.s
.PHONY : main.cpp.s

src/base.o: src/base.cpp.o
.PHONY : src/base.o

# target to build an object file
src/base.cpp.o:
	$(MAKE) -f CMakeFiles/feature.dir/build.make CMakeFiles/feature.dir/src/base.cpp.o
.PHONY : src/base.cpp.o

src/base.i: src/base.cpp.i
.PHONY : src/base.i

# target to preprocess a source file
src/base.cpp.i:
	$(MAKE) -f CMakeFiles/feature.dir/build.make CMakeFiles/feature.dir/src/base.cpp.i
.PHONY : src/base.cpp.i

src/base.s: src/base.cpp.s
.PHONY : src/base.s

# target to generate assembly for a file
src/base.cpp.s:
	$(MAKE) -f CMakeFiles/feature.dir/build.make CMakeFiles/feature.dir/src/base.cpp.s
.PHONY : src/base.cpp.s

src/blur.o: src/blur.cpp.o
.PHONY : src/blur.o

# target to build an object file
src/blur.cpp.o:
	$(MAKE) -f CMakeFiles/feature.dir/build.make CMakeFiles/feature.dir/src/blur.cpp.o
.PHONY : src/blur.cpp.o

src/blur.i: src/blur.cpp.i
.PHONY : src/blur.i

# target to preprocess a source file
src/blur.cpp.i:
	$(MAKE) -f CMakeFiles/feature.dir/build.make CMakeFiles/feature.dir/src/blur.cpp.i
.PHONY : src/blur.cpp.i

src/blur.s: src/blur.cpp.s
.PHONY : src/blur.s

# target to generate assembly for a file
src/blur.cpp.s:
	$(MAKE) -f CMakeFiles/feature.dir/build.make CMakeFiles/feature.dir/src/blur.cpp.s
.PHONY : src/blur.cpp.s

src/blurCombine.o: src/blurCombine.cpp.o
.PHONY : src/blurCombine.o

# target to build an object file
src/blurCombine.cpp.o:
	$(MAKE) -f CMakeFiles/feature.dir/build.make CMakeFiles/feature.dir/src/blurCombine.cpp.o
.PHONY : src/blurCombine.cpp.o

src/blurCombine.i: src/blurCombine.cpp.i
.PHONY : src/blurCombine.i

# target to preprocess a source file
src/blurCombine.cpp.i:
	$(MAKE) -f CMakeFiles/feature.dir/build.make CMakeFiles/feature.dir/src/blurCombine.cpp.i
.PHONY : src/blurCombine.cpp.i

src/blurCombine.s: src/blurCombine.cpp.s
.PHONY : src/blurCombine.s

# target to generate assembly for a file
src/blurCombine.cpp.s:
	$(MAKE) -f CMakeFiles/feature.dir/build.make CMakeFiles/feature.dir/src/blurCombine.cpp.s
.PHONY : src/blurCombine.cpp.s

src/feature.o: src/feature.cpp.o
.PHONY : src/feature.o

# target to build an object file
src/feature.cpp.o:
	$(MAKE) -f CMakeFiles/feature.dir/build.make CMakeFiles/feature.dir/src/feature.cpp.o
.PHONY : src/feature.cpp.o

src/feature.i: src/feature.cpp.i
.PHONY : src/feature.i

# target to preprocess a source file
src/feature.cpp.i:
	$(MAKE) -f CMakeFiles/feature.dir/build.make CMakeFiles/feature.dir/src/feature.cpp.i
.PHONY : src/feature.cpp.i

src/feature.s: src/feature.cpp.s
.PHONY : src/feature.s

# target to generate assembly for a file
src/feature.cpp.s:
	$(MAKE) -f CMakeFiles/feature.dir/build.make CMakeFiles/feature.dir/src/feature.cpp.s
.PHONY : src/feature.cpp.s

src/featureCompute.o: src/featureCompute.cpp.o
.PHONY : src/featureCompute.o

# target to build an object file
src/featureCompute.cpp.o:
	$(MAKE) -f CMakeFiles/feature.dir/build.make CMakeFiles/feature.dir/src/featureCompute.cpp.o
.PHONY : src/featureCompute.cpp.o

src/featureCompute.i: src/featureCompute.cpp.i
.PHONY : src/featureCompute.i

# target to preprocess a source file
src/featureCompute.cpp.i:
	$(MAKE) -f CMakeFiles/feature.dir/build.make CMakeFiles/feature.dir/src/featureCompute.cpp.i
.PHONY : src/featureCompute.cpp.i

src/featureCompute.s: src/featureCompute.cpp.s
.PHONY : src/featureCompute.s

# target to generate assembly for a file
src/featureCompute.cpp.s:
	$(MAKE) -f CMakeFiles/feature.dir/build.make CMakeFiles/feature.dir/src/featureCompute.cpp.s
.PHONY : src/featureCompute.cpp.s

src/lbpMine.o: src/lbpMine.cpp.o
.PHONY : src/lbpMine.o

# target to build an object file
src/lbpMine.cpp.o:
	$(MAKE) -f CMakeFiles/feature.dir/build.make CMakeFiles/feature.dir/src/lbpMine.cpp.o
.PHONY : src/lbpMine.cpp.o

src/lbpMine.i: src/lbpMine.cpp.i
.PHONY : src/lbpMine.i

# target to preprocess a source file
src/lbpMine.cpp.i:
	$(MAKE) -f CMakeFiles/feature.dir/build.make CMakeFiles/feature.dir/src/lbpMine.cpp.i
.PHONY : src/lbpMine.cpp.i

src/lbpMine.s: src/lbpMine.cpp.s
.PHONY : src/lbpMine.s

# target to generate assembly for a file
src/lbpMine.cpp.s:
	$(MAKE) -f CMakeFiles/feature.dir/build.make CMakeFiles/feature.dir/src/lbpMine.cpp.s
.PHONY : src/lbpMine.cpp.s

src/ldaMine.o: src/ldaMine.cpp.o
.PHONY : src/ldaMine.o

# target to build an object file
src/ldaMine.cpp.o:
	$(MAKE) -f CMakeFiles/feature.dir/build.make CMakeFiles/feature.dir/src/ldaMine.cpp.o
.PHONY : src/ldaMine.cpp.o

src/ldaMine.i: src/ldaMine.cpp.i
.PHONY : src/ldaMine.i

# target to preprocess a source file
src/ldaMine.cpp.i:
	$(MAKE) -f CMakeFiles/feature.dir/build.make CMakeFiles/feature.dir/src/ldaMine.cpp.i
.PHONY : src/ldaMine.cpp.i

src/ldaMine.s: src/ldaMine.cpp.s
.PHONY : src/ldaMine.s

# target to generate assembly for a file
src/ldaMine.cpp.s:
	$(MAKE) -f CMakeFiles/feature.dir/build.make CMakeFiles/feature.dir/src/ldaMine.cpp.s
.PHONY : src/ldaMine.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... feature"
	@echo "... imageParser"
	@echo "... rebuild_cache"
	@echo "... clcnst/clcnst.o"
	@echo "... clcnst/clcnst.i"
	@echo "... clcnst/clcnst.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/base.o"
	@echo "... src/base.i"
	@echo "... src/base.s"
	@echo "... src/blur.o"
	@echo "... src/blur.i"
	@echo "... src/blur.s"
	@echo "... src/blurCombine.o"
	@echo "... src/blurCombine.i"
	@echo "... src/blurCombine.s"
	@echo "... src/feature.o"
	@echo "... src/feature.i"
	@echo "... src/feature.s"
	@echo "... src/featureCompute.o"
	@echo "... src/featureCompute.i"
	@echo "... src/featureCompute.s"
	@echo "... src/lbpMine.o"
	@echo "... src/lbpMine.i"
	@echo "... src/lbpMine.s"
	@echo "... src/ldaMine.o"
	@echo "... src/ldaMine.i"
	@echo "... src/ldaMine.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

