# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_ALL_INSTALL_TYPES "Full")
SET(CPACK_BINARY_BUNDLE "")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "")
SET(CPACK_BINARY_DRAGNDROP "")
SET(CPACK_BINARY_NSIS "")
SET(CPACK_BINARY_OSXX11 "")
SET(CPACK_BINARY_PACKAGEMAKER "")
SET(CPACK_BINARY_RPM "")
SET(CPACK_BINARY_STGZ "")
SET(CPACK_BINARY_TBZ2 "")
SET(CPACK_BINARY_TGZ "")
SET(CPACK_BINARY_TZ "")
SET(CPACK_BINARY_WIX "")
SET(CPACK_BINARY_ZIP "")
SET(CPACK_CMAKE_GENERATOR "Unix Makefiles")
SET(CPACK_COMPONENTS_ALL "main;src;Unspecified")
SET(CPACK_COMPONENTS_ALL_SET_BY_USER "TRUE")
SET(CPACK_COMPONENT_MAIN_INSTALL_TYPES "Full")
SET(CPACK_COMPONENT_SRC_INSTALL_TYPES "Full")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_COMPONENT_main_DISPLAY_NAME "Binaries and the Documentation")
SET(CPACK_COMPONENT_src_DISPLAY_NAME "The source code")
SET(CPACK_GENERATOR "TBZ2")
SET(CPACK_IGNORE_FILES "/\\.svn/;/autom4te.cache/;/build/;/lib/;~$;\\.aux$;\\.bbl$;\\.blg$;\\.idx$;\\.ilg$;\\.ind$;\\.log$;\\.toc$;\\.out$;\\.vcproj$;/1$;")
SET(CPACK_INSTALLED_DIRECTORIES "/home/yx/fr/project/imageParser/vosm-0.3.3;/")
SET(CPACK_INSTALL_CMAKE_PROJECTS "")
SET(CPACK_INSTALL_PREFIX "/usr/local")
SET(CPACK_MODULE_PATH "")
SET(CPACK_NSIS_DISPLAY_NAME "vosm0.3")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
SET(CPACK_NSIS_PACKAGE_NAME "vosm0.3")
SET(CPACK_OUTPUT_CONFIG_FILE "/home/yx/fr/project/imageParser/vosm-0.3.3/CPackConfig.cmake")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-2.8/Templates/CPack.GenericDescription.txt")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "VOSM SDK for Unix Makefiles is an vosm based open source for developing statistical models")
SET(CPACK_PACKAGE_EXECUTABLES "")
SET(CPACK_PACKAGE_FILE_NAME "vosm-0.3.2")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "vosm0.3")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "vosm0.3")
SET(CPACK_PACKAGE_NAME "VOSM")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "VOSM project Vision Open Statistical Models")
SET(CPACK_PACKAGE_VERSION "0.3.2")
SET(CPACK_PACKAGE_VERSION_MAJOR "0")
SET(CPACK_PACKAGE_VERSION_MINOR "3")
SET(CPACK_PACKAGE_VERSION_PATCH "2")
SET(CPACK_RESOURCE_FILE_LICENSE "/home/yx/fr/project/imageParser/vosm-0.3.3/doc/license.txt")
SET(CPACK_RESOURCE_FILE_README "/usr/share/cmake-2.8/Templates/CPack.GenericDescription.txt")
SET(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-2.8/Templates/CPack.GenericWelcome.txt")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "TBZ2")
SET(CPACK_SOURCE_IGNORE_FILES "/\\.svn/;/autom4te.cache/;/build/;/lib/;~$;\\.aux$;\\.bbl$;\\.blg$;\\.idx$;\\.ilg$;\\.ind$;\\.log$;\\.toc$;\\.out$;\\.vcproj$;/1$;")
SET(CPACK_SOURCE_INSTALLED_DIRECTORIES "/home/yx/fr/project/imageParser/vosm-0.3.3;/")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/yx/fr/project/imageParser/vosm-0.3.3/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_PACKAGE_FILE_NAME "vosm-0.3.2")
SET(CPACK_SOURCE_TBZ2 "")
SET(CPACK_SOURCE_TGZ "")
SET(CPACK_SOURCE_TOPLEVEL_TAG "Linux-Source")
SET(CPACK_SOURCE_TZ "")
SET(CPACK_SOURCE_ZIP "")
SET(CPACK_STRIP_FILES "")
SET(CPACK_SYSTEM_NAME "Linux")
SET(CPACK_TOPLEVEL_TAG "Linux-Source")
SET(CPACK_WIX_SIZEOF_VOID_P "8")
